name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  essentials:
    name: ğŸ› ï¸ essentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/check_draft
      - uses: ./templates/check_conflicts
      - uses: ./templates/check_merge

  lint:
    name: ğŸ§ Linting
    runs-on: ubuntu-latest
    needs: essentials
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/lint

  docs:
    name: ğŸ“ Documentation
    runs-on: ubuntu-latest
    needs: essentials
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/check_docs

  security_scan:
    name: ğŸ›¡ï¸ Secutiry Scan
    runs-on: ubuntu-latest
    needs: [lint, docs]
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/security_scan

  template_validate:
    name: ğŸ‘ Template Validate
    runs-on: ubuntu-latest
    needs: [security_scan]
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/template_validate

  tag_release:
    name: ğŸ·ï¸ Generanting Tag Release
    runs-on: ubuntu-latest
    needs: [template_validate]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./templates/tag_release
