name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  essentials:
    name: ğŸ› ï¸ essentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/check_draft
      - uses: ./templates/check_conflicts
      - uses: ./templates/check_merge

  lint:
    name: ğŸ§ Linting
    runs-on: ubuntu-latest
    needs: essentials
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/lint

  docs:
    name: ğŸ“ Documentation
    runs-on: ubuntu-latest
    needs: essentials
    steps:
      - uses: actions/checkout@v4
      - uses: ./templates/check_docs
